cfg = {
    # 'dataset_dir': '/viscam/u/yenyu/ObjectFolderV2/objects/23/VisionNet_osf_data/',
    # 'pretrained_cfg_path': '/viscam/u/yenyu/kiloosf2/cfgs/paper/pretrain/23.yaml',
    # 'pretrained_checkpoint_path': '/viscam/u/yenyu/kiloosf2/logs/paper/pretrain/23/checkpoint_0200000.pth',
    'blender_half_res': False,
    'dataset_type': 'osf',
    'discovery': {
        'alpha_distance': 0.0211,
        'alpha_rgb_initalization': 'pass_actual_nonlinearity',
        'bias_initialization_method': 'standard',
        'convert_density_to_alpha': True,
        'direction_layer_size': 64,
        'equal_split_metric': 'mse',
        'hidden_layer_size': 64,
        'iterations': 30000,
        'late_feed_direction': True,
        'max_num_networks': 512,
        'network_rng_seed': 8078673,
        'nonlinearity_initalization': 'pass_actual_nonlinearity',
        'num_examples_per_network': 1020000,
        'num_frequencies': 10,
        'num_frequencies_direction': 4,
        'num_frequencies_light': 4,
        'num_hidden_layers': 2,
        'num_train_examples_per_network': 1000000,
        'outputs': 'color_and_density',
        'quantile_se': 0.99,
        'query_batch_size': 80000,
        'refeed_position_index': 'None',
        'test_batch_size': 512,
        'test_error_metric': 'quantile_se',
        'test_every': 500, 'train_batch_size': 128,
        'use_same_initialization_for_all_networks': True,
        'weight_initialization_method': 'kaiming_uniform'
    },
    'fixed_resolution': [16, 16, 16],
    'max_error': 100000,
    'performance_monitoring': False,
    'render_only': True,
    'restart_after_checkpoint': True,
    'skip_final': True,
    'tree_type': 'kdtree_longest',
    'global_domain_min': [-0.6, -0.6, -0.6],
    'global_domain_max': [0.6, 0.6, 0.6],
    'alpha_distance': 0.0211,
    'alpha_rgb_initalization': 'pass_actual_nonlinearity',
    'bias_initialization_method': 'standard',
    'convert_density_to_alpha': True,
    'direction_layer_size': 64,
    'equal_split_metric': 'mse',
    'hidden_layer_size': 64,
    'iterations': 1000000,
    'late_feed_direction': True,
    'max_num_networks': 512,
    'network_rng_seed': 8078673,
    'nonlinearity_initalization': 'pass_actual_nonlinearity',
    'num_examples_per_network': 1020000,
    'num_frequencies': 10,
    'num_frequencies_direction': 4,
    'num_frequencies_light': 4,
    'num_hidden_layers': 2,
    'num_train_examples_per_network': 1000000,
    'outputs': 'color_and_density',
    'quantile_se': 0.99,
    'query_batch_size': 80000,
    'refeed_position_index': 'None',
    'test_batch_size': 512,
    'test_error_metric': 'quantile_se',
    'test_every': 500,
    'train_batch_size': 128,
    'use_same_initialization_for_all_networks': False,
    'weight_initialization_method': 'kaiming_uniform',
    # 'distilled_cfg_path': '/viscam/u/yenyu/kiloosf2/cfgs/paper/distill/23.yaml',
    # 'distilled_checkpoint_path': '/viscam/u/yenyu/kiloosf2/logs/paper/distill/23/checkpoint.pth',
    # 'occupancy_cfg_path': '/viscam/u/yenyu/kiloosf2/cfgs/paper/pretrain_occupancy/23.yaml',
    # 'occupancy_log_path': '/viscam/u/yenyu/kiloosf2/logs/paper/pretrain_occupancy/23/occupancy.pth',
    'checkpoint_interval': 50000,
    'chunk_size': 40000,
    'initial_learning_rate': 0.001,
    'l2_regularization_lambda': 1e-06,
    'learing_rate_decay_rate': 500,
    'no_batching': True,
    'num_rays_per_batch': 8192,
    'num_samples_per_ray': 384,
    'perturb': 1.0,
    'precrop_fraction': 0.5,
    'precrop_iterations': 0,
    'raw_noise_std': 0.0,
    'near': 0.01,
    'far': 4,
    'spiral_radius': None,
    'half_res': False,
    'n_render_spiral': 40,
    'render_spiral_angles': None,
    'num_importance_samples_per_ray': 0,
    'render_test': True,
    'no_color_sigmoid': False,
    'render_factor': 0,
    'testskip': 1,
    'deepvoxels_shape': 'greek',
    'blender_white_background': True,
    'llff_factor': 8,
    'llff_no_ndc': False,
    'llff_lindisp': False,
    'llff_spherify': False,
    'llff_hold': False,
    'print_interval': 100,
    'render_testset_interval': 100000,
    'render_video_interval': 100000000,
    'network_chunk_size': 65536,
    'rng_seed': 0,
    'use_initialization_fix': False,
    'model_type': 'multi_network',
    'random_direction_probability': -1,
    'von_mises_kappa': -1,
    'view_dependent_dropout_probability': -1,
    'occupancy': {
        # 'dataset_dir': '/viscam/u/yenyu/ObjectFolderV2/objects/23/VisionNet_osf_data/',
        'dataset_type': 'osf',
        # 'pretrained_cfg_path': '/viscam/u/yenyu/kiloosf2/cfgs/paper/pretrain/23.yaml',
        # 'pretrained_checkpoint_path': '/viscam/u/yenyu/kiloosf2/logs/paper/pretrain/23/checkpoint_0200000.pth',
        'resolution': [256, 256, 256],
        'subsample_resolution': [3, 3, 3],
        'threshold': 10,
        'voxel_batch_size': 16384,
        'global_domain_min': [-0.6, -0.6, -0.6],
        'global_domain_max': [0.6, 0.6, 0.6]
    }
}
